# Generated by Django 3.0.8 on 2020-08-19 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_pledge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pledge',
            old_name='anonnymous',
            new_name='anonymous',
        ),
    ]
