# Generated by Django 3.0.8 on 2020-08-22 01:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trips', '0004_auto_20200819_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledge',
            name='trip_mate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_mate_pledges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trip',
            name='organiser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organiser_trips', to=settings.AUTH_USER_MODEL),
        ),
    ]
